name = "porto"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

# KV Namespace Binding
[[kv_namespaces]]
binding = "BLOG_KV"
id = "BLOG_KV_ID" # This is a placeholder ID for local dev

# R2 Bucket Binding
[[r2_buckets]]
binding = "BLOG_BUCKET"
bucket_name = "blog-images"
