name: 'Setup Environment'
description: 'Checkout repository, Setup Bun, and Install Dependencies'

inputs:
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags.'
    required: false
    default: '1'
  persist-credentials:
    description: 'Whether to configure the token or SSH key with the local git config'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        persist-credentials: ${{ inputs.persist-credentials == 'true' }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      shell: bash
      run: bun install
