name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Verify Quasar CLI
        run: bunx quasar info

      - name: Lint
        run: bun run lint

      - name: Type Check
        run: bun run type-check

      - name: Unit Tests
        run: bun run test

      - name: Build
        run: bun run build
