name: CI

on:
  workflow_call:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment


      - name: Lint
        run: bun run lint

      - name: Type Check
        run: bun run type-check

      - name: Run test analytics
        run: bunx vitest run --reporter=junit --outputFile=coverage/test-report.junit.xml

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/test-report.junit.xml
          report_type: test_results
          fail_ci_if_error: true

      - name: Run tests with coverage
        run: bunx vitest run --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: true

      - name: Build
        run: bun run build
