name: Release

on:
  workflow_call:

permissions:
  contents: write # needed to create github release and push to main
  issues: write   # needed for semantic-release to comment on issues
  pull-requests: write # needed for semantic-release to comment on PRs

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required by semantic-release to gather commit history
          persist-credentials: false # Uses semantic-release for pushing instead

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bunx semantic-release
